### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hyandell** [mulesoft-labs/raml-json-validation#1]
Hi Mulesoft,

What's the license on this repository?

You seem to generally use Apache 2.0, though I also couldn't identify the license for https://github.com/mulesoft-labs/raml-suggestions

**Comment by jstoiko** [comment]
@hyandell: the License has been added.

**Comment by hyandell** [comment]
Thank you.

You've included a CC-BY license on the end of the Apache-2.0; I'll assume that was intentional.
